@InventoryApi_HostAddress = https://localhost:7153

POST {{InventoryApi_HostAddress}}/products
Content-Type: application/json

{
  "name": "Raspberries",
  "price": 3.99,
  "stock": 100,
  "isActive": false
}

###

POST {{InventoryApi_HostAddress}}/products
Content-Type: application/json
{
  "name": "Bananas",
  "price": 1.99,
  "stock": 30,
  "isActive": true
}

###

PATCH {{InventoryApi_HostAddress}}/products/1
Content-Type: application/json
{
  "stock": 15,
  "description": "Tasty red apples"
}


###

PATCH {{InventoryApi_HostAddress}}/products/1/deactivate

###

POST {{InventoryApi_HostAddress}}/customers
Content-Type: application/json
{
  "name": "Julián Sierra",
  "email": "julian.sierra@gmail.com",
  "address": "calle 123",
  "phone": "+34 123456789"
}

###

PATCH {{InventoryApi_HostAddress}}/customers/1
Content-Type: application/json
{
  "address": "rua 123",
  "phone": "+351 123456789"
}

###

PATCH {{InventoryApi_HostAddress}}/orders/1/status
Content-Type: application/json
{
  "status": "cancelled"
}

###

POST {{InventoryApi_HostAddress}}/orders
Content-Type: application/json
{
  "customerId": 1,
  "orderItems": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 2,
      "quantity": 5
    }
  ]
}

###