using Microsoft.EntityFrameworkCore;
using InventoryApi.Data;
using InventoryApi.Models;
using InventoryApi.DTOs.Products;
using InventoryApi.DTOs.Customers;
using System.Runtime.CompilerServices;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<AppDbContext>(options =>
        options.UseSqlite(builder.Configuration.GetConnectionString("DefaultConnection")));
builder.Services.AddDatabaseDeveloperPageExceptionFilter();
var app = builder.Build();

CreateDbIfNotExists(app);

app.MapGet("/products", async (AppDbContext db) =>
    await db.Products.Select(x => new ProductDTO(x)).ToListAsync());

app.MapGet("/products/{id:int}", async (int id, AppDbContext db) =>
    await db.Products.FindAsync(id)
        is Product product
            ? Results.Ok(new ProductDTO(product))
            : Results.NotFound());

app.MapPost("/products", async (ProductCreateDTO createProduct, AppDbContext db) =>
{
    Product product = new Product {
        Name = createProduct.Name,
        Description = createProduct.Description,
        Price = createProduct.Price,
        Stock = createProduct.Stock,
        IsActive = createProduct.IsActive
    };

    if (string.IsNullOrWhiteSpace(product.Name)) 
        return Results.BadRequest("Product name is required.");

    if (product.Price < 0)
        return Results.BadRequest("Price cannot be negative.");

    if (product.Stock < 0)
        return Results.BadRequest("Stock cannot be negative.");

    //product.Id = 0; // Ensure the ID is generated by the database

    db.Products.Add(product);
    await db.SaveChangesAsync();
    return Results.Created($"/products/{product.Id}", product);
});

app.MapPatch("/products/{id:int}", async (int id, ProductPatchDTO patchedProduct, AppDbContext db) =>
{
    var product = await db.Products.FindAsync(id);

    if (product is null) return Results.NotFound();

    if (patchedProduct.Name is not null)        product.Name = patchedProduct.Name;
    if (patchedProduct.Description is not null) product.Description = patchedProduct.Description;
    if (patchedProduct.Price is not null)       product.Price = patchedProduct.Price.Value;
    if (patchedProduct.Stock is not null)       product.Stock = patchedProduct.Stock.Value;
    if (patchedProduct.IsActive is not null)    product.IsActive = patchedProduct.IsActive.Value;

    if (string.IsNullOrWhiteSpace(product.Name))
        return Results.BadRequest("Product name is required.");

    if (product.Price < 0)
        return Results.BadRequest("Price cannot be negative.");

    if (product.Stock < 0)
        return Results.BadRequest("Stock cannot be negative.");

    await db.SaveChangesAsync();

    return Results.NoContent();
});

app.MapPatch("/products/{id:int}/deactivate", async (int id, AppDbContext db) =>
{
    var product = await db.Products.FindAsync(id);

    if (product is null) return Results.NotFound();

    product.IsActive = false;

    await db.SaveChangesAsync();
    return Results.NoContent();
});

app.MapGet("/customers", async (AppDbContext db) =>
    await db.Customers.Select(x => new CustomerDTO(x)).ToListAsync());

app.MapGet("/customers/{id:int}", async (int id, AppDbContext db) =>
    await db.Customers.FindAsync(id)
        is Customer customer
            ? Results.Ok(new CustomerDTO(customer))
            : Results.NotFound());

app.MapPost("/customers", async (CustomerCreateDTO createCustomer, AppDbContext db) =>
{
    Customer customer = new Customer {
        Name = createCustomer.Name,
        Email = createCustomer.Email,
        Address = createCustomer.Address,
        Phone = createCustomer.Phone
    };

    if (string.IsNullOrWhiteSpace(customer.Name))
        return Results.BadRequest("Customer name is required.");
    if (string.IsNullOrWhiteSpace(customer.Email))
        return Results.BadRequest("Customer email is required.");

    db.Customers.Add(customer);
    await db.SaveChangesAsync();

    return Results.Created($"/customers/{customer.Id}", customer);
});

app.MapPatch("/customers/{id:int}", async (int id, CustomerPatchDTO patchedCustomer, AppDbContext db) =>
{
    var customer = await db.Customers.FindAsync(id);

    if (customer is null) return Results.NotFound();

    if (patchedCustomer.Name is not null)     customer.Name = patchedCustomer.Name;
    if (patchedCustomer.Email is not null)    customer.Email = patchedCustomer.Email;
    if (patchedCustomer.Address is not null)  customer.Address = patchedCustomer.Address;
    if (patchedCustomer.Phone is not null)    customer.Phone = patchedCustomer.Phone;

    if (string.IsNullOrWhiteSpace(customer.Name))
        return Results.BadRequest("Customer name is required.");
    if (string.IsNullOrWhiteSpace(customer.Email))
        return Results.BadRequest("Customer email is required.");

    await db.SaveChangesAsync();
    return Results.NoContent();
});

app.MapGet("/", () => "Hello World!");

app.Run();

static void CreateDbIfNotExists(WebApplication app)
{
    using (var scope = app.Services.CreateScope())
    {
        var services = scope.ServiceProvider;
        try
        {
            var context = services.GetRequiredService<AppDbContext>();
            DbInitializer.Initialize(context);
        }
        catch (Exception ex)
        {
            var logger = services.GetRequiredService<ILogger<Program>>();
            logger.LogError(ex, "An error occurred creating the DB.");
        }
    }
}
