using Microsoft.EntityFrameworkCore;
using InventoryApi.Data;
using InventoryApi.Models;
using InventoryApi.DTOs.Products;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseInMemoryDatabase("InventoryApiDb"));
builder.Services.AddDatabaseDeveloperPageExceptionFilter();
var app = builder.Build();

// Seed the in-memory database with initial mock data
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    if (!dbContext.Products.Any())
    {
        dbContext.Products.AddRange(
            new Product { Name = "Apples", Price = 1.20m, Stock = 100, IsActive = true },
            new Product { Name = "Bread", Price = 0.95m, Stock = 50, IsActive = true },
            new Product { Name = "Fish", Price = 5.49m, Stock = 17 , IsActive = true }
    );
        dbContext.SaveChanges();
    }
}

app.MapGet("/products", async (AppDbContext db) =>
    await db.Products.Select(x => new ProductDTO(x)).ToListAsync());

app.MapGet("/products/{id:int}", async (int id, AppDbContext db) =>
    await db.Products.FindAsync(id)
        is Product product
            ? Results.Ok(new ProductDTO(product))
            : Results.NotFound());

app.MapPost("/products", async (ProductCreateDTO createProduct, AppDbContext db) =>
{
    Product product = new Product {
        Name = createProduct.Name,
        Description = createProduct.Description,
        Price = createProduct.Price,
        Stock = createProduct.Stock,
        IsActive = createProduct.IsActive
    };

    if (string.IsNullOrWhiteSpace(product.Name)) 
        return Results.BadRequest("Product name is required.");

    if (product.Price < 0)
        return Results.BadRequest("Price cannot be negative.");

    if (product.Stock < 0)
        return Results.BadRequest("Stock cannot be negative.");

    //product.Id = 0; // Ensure the ID is generated by the database

    db.Products.Add(product);
    await db.SaveChangesAsync();
    return Results.Created($"/products/{product.Id}", product);
});

app.MapPatch("/products/{id:int}", async (int id, ProductPatchDTO patchedProduct, AppDbContext db) =>
{
    var product = await db.Products.FindAsync(id);

    if (product is null) return Results.NotFound();

    if (patchedProduct.Name is not null)        product.Name = patchedProduct.Name;
    if (patchedProduct.Description is not null) product.Description = patchedProduct.Description;
    if (patchedProduct.Price is not null)       product.Price = patchedProduct.Price.Value;
    if (patchedProduct.Stock is not null)       product.Stock = patchedProduct.Stock.Value;
    if (patchedProduct.IsActive is not null)    product.IsActive = patchedProduct.IsActive.Value;

    if (string.IsNullOrWhiteSpace(product.Name))
        return Results.BadRequest("Product name is required.");

    if (product.Price < 0)
        return Results.BadRequest("Price cannot be negative.");

    if (product.Stock < 0)
        return Results.BadRequest("Stock cannot be negative.");

    await db.SaveChangesAsync();

    return Results.NoContent();
});

app.MapPatch("/products/{id:int}/deactivate", async (int id, AppDbContext db) =>
{
    var product = await db.Products.FindAsync(id);

    if (product is null) return Results.NotFound();

    product.IsActive = false;

    await db.SaveChangesAsync();
    return Results.NoContent();
});

app.MapGet("/", () => "Hello World!");

app.Run();
